# Generated by Django 4.0.6 on 2022-07-31 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComboCotillon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad_personas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Copetin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('tipo_de_producto', models.CharField(max_length=50)),
                ('peso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Disfraz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('talle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Golosinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('tipo_de_producto', models.CharField(max_length=50)),
                ('unidades', models.IntegerField()),
            ],
        ),
    ]
