# Generated by Django 4.0.6 on 2022-08-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Proyecto_final', '0002_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='golosinas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='golosinass'),
        ),
    ]
