# Generated by Django 4.0.6 on 2022-08-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Proyecto_final', '0005_combocotillon_user_copetin_user_disfraz_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combocotillon',
            name='precio',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='copetin',
            name='precio',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disfraz',
            name='precio',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='golosinas',
            name='precio',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
