# Generated by Django 4.0.6 on 2022-08-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Proyecto_final', '0006_combocotillon_precio_copetin_precio_disfraz_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combocotillon',
            name='descripcion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='copetin',
            name='descripcion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disfraz',
            name='descripcion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='golosinas',
            name='descripcion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
